# Site settings
title: Benoit TRAVERS
email: benoit.travers.fr@gmail.com
description: Listing of btravers' projects.
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: btravers
github_username:  btravers

# Build settings
markdown: kramdown
collections:
  - projects
