# Site settings
title: Benoit TRAVERS
email: benoit.travers.fr@gmail.com
description: Listing of btravers' projects.
baseurl: ""
twitter_username: btravers
github_username:  btravers

# Build settings
markdown: kramdown
collections:
  - projects
