packages:
  - "."

minimumReleaseAge: 0

allowBuilds:
  esbuild: true

catalog:
  vitepress: 1.6.4
  vue: 3.5.39
  sort-package-json: 4.0.0
  oxfmt: 0.56.0
  oxlint: 1.71.0
  typescript: 6.0.3
  vue-tsc: 3.3.5
  "@types/node": 24.13.2
